### PR TITLE
Add minified classie.min.js

### PR DESCRIPTION
**Pull request by hubdotcom**
Minified with UglifyJS 2: http://refresh-sf.com

Input: 1.97 KB
Output: 967 bytes

Over 50% saving and classie is now less than 1KB!

### CODE REVIEW

**Comment by desandro** [comment]
Thanks for this contribution. classie.js is a small library to begin with. I don't feel that saving 1 kb is worth adding another file to the repo. I appreciate your effort here, but I'll have to pass.

**Comment by hubdotcom** [comment]
I see, I was preparing it for inclusion in http://www.jsdelivr.com (new libraries are required to upload just the .min.js for production use)

**Comment by desandro** [comment]
I recommend using classie as a component library. Adding it to CDN's gives the impression that you should added with its own `<script>`. I'd prefer if you use it with your own build tools to produce compiled files.

**Comment by hubdotcom** [comment]
Fair enough, will keep it off the CDN :+1:

**Pull request closed without merging**
